### ISSUE TITLE
Discussion: Allow for invalidation without recomputation

### ISSUE THREAD

**Issue by anhaehne** [servicetitan/Stl.Fusion#178]
In real world application we do not control all the data we need to display in our applications and therefore don't know when they have updated. Let's take a 3rd party Api for example. 

We could of cause invalidate the data every n minutes but that would trigger a complete recomputation of our user interface (or at least the parts that are effected). 

It would be great if we had some kind of mechanism to invalidate the cached result of a ComputedMethod without triggering recomputation but instead, reevaluate the Method the next time the result is needed. 

This would have to work all the way up to so the next layer would't just be cached.

**Comment by alexyakunin** [comment]
Hi @anhaehne , that's exactly how it works, actually :) Invalidation never means recomputation in Fusion.

**Comment by alexyakunin** [comment]
But I guess your question is more practical, i.e. you are talking about some real problem you've faced, but probably your assumptions about what Fusion does aren't absolutely correct. 

If you're fine with explaining what you want to implement, I'll try to describe the best way to do this + explain what Fusion does in your specific case. Feel free to reach me out on Discord (AY) & PM the link to code.

**Comment by alexyakunin** [comment]
A couple useful links:
- https://github.com/servicetitan/Stl.Fusion.Samples/blob/master/docs/tutorial/Part03.md - check out the part about ILiveState
- https://github.com/servicetitan/Stl.Fusion.Samples/blob/master/docs/tutorial/Part06.md - prob. makes sense to read everything here

**Comment by anhaehne** [comment]
Lets say i have multiple drop downs in my ui and based on that i aggregate data from multiple source. One of those sources is a WebApi which i don't have control over. The aggregated result then displayed in my application.

So the dependency graph would look something like this: 
```
 +--------------+                                 +---------------+
 |UI-Controls   +<----------+            +------->+Some WebApi    |
 |              |           |            |        |               |
 +--------------+           |            |        +---------------+
                            |            |
 +--------------+         +---------------+       +---------------+
 |UI-Display    +-------->+Aggregate-Service      |My Backend     |
 |              |         |               |------>+               |
 +--------------+         +---------------+       +---------------+
```
So when the controls get changed, the Aggregate-Service fetches the data from the Backend and a 3rd party WebApi. Both would be ComputedMethods. Since there is no way the the call to WebApi is invalidated, the cached result would be used all the time. 

If i invalidate the fetch call to WebApi, the ComputedMethod in the Aggregate-Service would be invalidated, which in turn would invalidate the ui and force it recalculate everthing.

**Comment by alexyakunin** [comment]
Got it. One way to implement this is:
- Implement a `[ComputeMethod]` that will serve expose external service's data in Fusion style. All it does is hits the external endpoint & returns whatever it gets from it. 
- Auto-invalidate the result of this method in T seconds. You can use e.g. `[ComputeService(AutoInvalidateTime = T)]` to achieve that. This will ensure the result of this method "expires" every T seconds.

Now, there is one problem with this approach. What if you invalidate the result, but the new result is actually still the same as the old one? As you imagine, such an invalidation will trigger cascading invalidation of every dependency, which isn't good. 

A good way to address this is to implement ~ the following pattert:
- On expiration of invalidation timeout: check if the new data is the same as the old one. Renew the expiration timer if it's still the same, and run the invalidation + ideally, make sure the endpoint gets the value we fetched on check instead of hitting the actual service twice on recompute.

**Comment by alexyakunin** [comment]
See e.g. `ScreenshotService` in samples to see how something similar can be done. There is no comparison, but it should be clear how it could be added.

As for the comparison, one of easy ways to implement it is to compare serialized values.

**Comment by alexyakunin** [comment]
And the last thing: yes, it's a pretty common problem / pattern, so maybe I'll add something to make the implementation of something similar much more straightforward.

**Comment by alexyakunin** [comment]
@anhaehne See my responses, + if you need some answers ASAP, [our Discord Server](https://discord.gg/EKEwv6d) is really the best option to have them. Just saying :)

**Comment by alexyakunin** [comment]
@anhaehne just added code sample to the key comment above.

**Comment by alexyakunin** [comment]
@anhaehne actually, just wrote a ~ complete sample above.

**Comment by alexyakunin** [comment]
As you imagine, there are many ways to achieve this:
- The code I wrote tackles a scenario where you don't want to periodically hit the external API if no one uses your own endpoint, i.e. it's a sort of "on demand extraction + invalidation".
- But there is another common scenario where you actually want to extract the data ahead of time / recurrently no matter what. And in this case I'd recommend to use `private IMutableState<Whatever> cachedValue` to store the last fetched value & have a compute method that simply returns its value & becomes dependent on it: `return cachedValue.UseAsync(cancellationToken);`

**Comment by anhaehne** [comment]
Thanks for your detailed awnser. I tried to replicate your code into a working program but it is still requesting the WebApi every n seconds. 

```
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Stl.Fusion;

namespace Stl.Fusion_test
{
    public class Program
    {
        private static async Task Main()
        {
            var s = new ServiceCollection();
            s.AddFusion().AddComputeService<MyService>().AddComputeService<MyAggregateService>();
            var sb = s.BuildServiceProvider();

            var stateFactory = sb.GetRequiredService<IStateFactory>();
            var myAggregateService = sb.GetRequiredService<MyAggregateService>();


            var live = stateFactory.NewLive<string>((_, ct) => myAggregateService.Aggregate());

            live.Updated += (s, _) => Console.WriteLine(s.Value);

            await Task.Delay(5000);

            myAggregateService.UiInput = "New Value";

            await Task.Delay(5000);
        }
    }

    public class MyAggregateService
    {
        private readonly MyService _myService;
        private string _uiInput = "Some Value";

        public MyAggregateService(MyService myService)
        {
            _myService = myService;
        }

        public string UiInput
        {
            get => _uiInput;
            set
            {
                _uiInput = value; 
                Computed.Invalidate(() => Aggregate());
            }
        }

        [ComputeMethod]
        public virtual async Task<string> Aggregate()
        {
            var serviceResult = await _myService.GetWebApiResultAsync();

            return $"{serviceResult} - {_uiInput}";
        }
    }

    public class MyService
    {
        [ComputeMethod]
        public virtual async Task<string> GetWebApiResultAsync()
        {
            var computed = Computed.GetCurrent();
            using var _ = Computed.Suppress(); // Suppresses dependency capture
            var result = await GetWebApiResultAsyncImpl();

            async Task MaybeInvalidate()
            {
                await Task.Delay(2000); // The delay here should be >= AutoInvalidateTime value above
                var mustInvalidate = true;

                try
                {
                    var newValue = await GetWebApiResultAsyncImpl();
                    mustInvalidate = IsChanged((string) computed.Value, newValue);
                }
                catch (Exception e)
                {
                }
                finally
                {
                    // One of actions below should be called no matter what, 
                    // otherwise GetWebApiResultAsync result will stay the same forever
                    if (mustInvalidate)
                        computed.Invalidate();
                    else
                        Task.Run(MaybeInvalidate);
                }
            }

            Task.Run(MaybeInvalidate);

            return result;
        }

        [ComputeMethod(KeepAliveTime = 1, AutoInvalidateTime = 1)] // Caches WebAPI call result for 1 second
        protected virtual async Task<string> GetWebApiResultAsyncImpl()
        {
            // Run the actual WebAPI request here
            Console.WriteLine("Executing GetWebApiResultAsyncImpl");

            return "Test";
        }

        private bool IsChanged(string a, string b)
        {
            return a == b;
        }
    }
}
```

It's OK for me if there is no solution right now. I just wanted to start a discussion about the scenario and ask whether this would fit into the framework.

**Comment by alexyakunin** [comment]
@anhaehne Hi, thanks for the example. The only issue in your code is `a == b` on the last line. I guess it's supposed to be `a != b` :)

I created a small repo w/ this code (maybe will turn it into a console example later) + diff to your logic (the only important change is the last line though): https://github.com/alexyakunin/Stl.Fusion.Misc/commit/2771441fcf40744ec9a84210b32c9c4f8ff25a95#diff-e6e6f3bd90d233666dc41c4a6778ffaee5b3f49ea5d179e7aa38552f4ac66902R110

Its output:

```text
Executing GetWebApiResultAsyncImpl
5: Test - Initial Value
5: Test - Initial Value
4: Test - Initial Value
4: Test - Initial Value
5: Test - Initial Value
Executing GetWebApiResultAsyncImpl
Executing GetWebApiResultAsyncImpl
5: Test - New Value
5: Test - New Value
4: Test - New Value
4: Test - New Value
5: Test - New Value
Executing GetWebApiResultAsyncImpl
Executing GetWebApiResultAsyncImpl
```

I.e. it does what it's supposed to do - it runs GetWebApiResultAsyncImpl every second to pull the new data, but never invalidates the result of GetWebApiResultAsync, because it's always the same data. I'll push a change showing it actually works as expected shortly.

**Comment by alexyakunin** [comment]
Check out https://github.com/alexyakunin/Stl.Fusion.Misc/commit/1824d18cb61897d35ca3c0168e151c5bffca56ac - it shows it actually triggers the invalidation when the new output differs from the old one.

**Comment by alexyakunin** [comment]
@anhaehne one other small thing: `ILiveState` is `IDisposable` - you have to use `using` with it, otherwise task completion subscriptions in its update loop will keep it in RAM indefinitely (and will continue processing the updates too).

**Comment by alexyakunin** [comment]
@anhaehne do you think it's fine to close this issue?

**Comment by anhaehne** [comment]
I haven't had time to look at you latest awnsers but i'm fine closing this issue.
