### ISSUE TITLE
Exponential growth of buffer size?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [servicetitan/Stl.Fusion#188]
I couldn't help to [notice here](https://github.com/servicetitan/Stl.Fusion/blob/1919aa8ea67fb9437c82fdd9c2844528fbbf2c3b/src/Stl/Collections/MemoryBuffer.cs#L115) that the buffer pool grows exponentially by a factor of 2... isn't that kinda dangerous? I mean, you should be fine for the first 10-12 bits, but after that you will start moving/copying fairly large portions of memory... 

Have you consider using a strategy similar to [RecyclableStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/master/src/RecyclableMemoryStreamManager.cs)? Where a pool of smaller buffers are provisioned and then concatenated when more memory is needed... The growth of the total allocated pool grows linearly (according to the `blockSize`) but the large buffers can also grow exponentially... This is the big gain over the `MemoryPool` by the way

**Comment by alexyakunin** [comment]
I used the usual impl. for variable-sized lists that provides O(1) time complexity (amortized) for Add operation while retaining the same O(1) for indexing. E.g. List<T> in .NET does almost exactly the same; AFAIK it's the best way to do this. Concatenating many buffers is definitely a better option, but you lose indexing perf. in this case. I will have a look at use cases though - and if I don't need indexing, I should definitely switch to a better option.

**Comment by alexyakunin** [comment]
https://github.com/servicetitan/Stl.Fusion/pull/189

**Comment by alexyakunin** [comment]
@Leonardo-Ferreira I merged the PR, please check out my comments there. Thanks!

**Comment by alexyakunin** [comment]
I am closing the issue, but if you feel something still has to changed there, please re-open it again or notify me.
