### ISSUE TITLE
Add MessagePack serializer support

### ISSUE THREAD

**Issue by alexyakunin** [servicetitan/Stl.Fusion#279]

**Comment by timeshift92** [comment]
looks  good
https://github.com/neuecc/MessagePack-CSharp#performance

**Comment by alexyakunin** [comment]
What's remaining here:
- Binary message format support in `WebSocketChannel` / `WebSocketChannelProvider` (used by the client) / `WebSocketServer` (used on the server side).

I guess the implementation implies we rename `SerializerXxx` to `TextSerializerXxx` there, add `ByteSerializerXxx`, and finally, + add an option controlling preferred message format (binary or text) on the client side.

**Comment by JoshuaNitschke** [comment]
Per our conversation on Discord, I am going to take a stab at this.

**Comment by alexyakunin** [comment]
Done, + MemoryPack as well :)
