### ISSUE TITLE
async alternate 

### ISSUE THREAD

**Issue by timeshift92** [servicetitan/Stl.Fusion#388]
excellent library, instead of asynchronous, you didn’t look towards fibers?
see please this repo https://github.com/hyoo-ru/mam_mol

**Comment by alexyakunin** [comment]
I guess this spam issue has to go.

**Comment by timeshift92** [comment]
Sorry if it turned out to be spam, but even dotnet used fibers before, net 4.5 used fibers

**Comment by alexyakunin** [comment]
@timeshift92 I realized it probably was a legit question (based on your other activity). If it's still important, please feel free to ask it on our Discord: https://discord.gg/EKEwv6d ; honestly, I don't know anything about mol, but maybe someone else there does.
