### ISSUE TITLE
infinite query loop

### ISSUE THREAD

**Issue by timeshift92** [servicetitan/Stl.Fusion#390]
https://github.com/timeshift92/StlUnlimitedRequestBug

![image](https://user-images.githubusercontent.com/13614530/147557355-62354ae9-5539-4643-8578-087fdcae75dc.png)

represent
```
cd Server
dotnet watch
```

**Comment by alexyakunin** [comment]
Hi, I guess this is what you mean:
![image](https://user-images.githubusercontent.com/1673423/147620243-07257e0a-2392-4689-be80-639a0d9c7346.png)

**Comment by alexyakunin** [comment]
Hi, I guess this is what you mean:
![image](https://user-images.githubusercontent.com/1673423/147620298-f2a56de1-0992-4b52-aea0-d68b175cda68.png)

**Comment by alexyakunin** [comment]
Just sharing how I live diagnose this :)

![image](https://user-images.githubusercontent.com/1673423/147620411-694b2c2d-f69a-42cb-9722-85ec88919bdd.png)

As you see, 200 OK response here is because there is a default route that always directs you to index / _Host.cshtml, so the controller isn't used or resolved.

**Comment by alexyakunin** [comment]
And if you go to Swagger page, you'll see why:

![image](https://user-images.githubusercontent.com/1673423/147620575-8ab661c8-d17d-4682-b8c3-adfba10fe980.png)

**Comment by alexyakunin** [comment]
The fix is to give endpoints proper names in the client definition interface:

```cs
[BasePath("counter")]
public interface ICounterClientDef
{
    [Post("Increment")]
    Task IncrementAsync(CancellationToken cancellationToken = default);

    [Get("GetCount")]
    Task<int> GetCountAsync(CancellationToken cancellationToken = default);
}
```

**Comment by alexyakunin** [comment]
![image](https://user-images.githubusercontent.com/1673423/147620768-7db56385-4fdb-4abf-8af5-f178c51a2544.png)

Works fine after this fix :)

**Comment by alexyakunin** [comment]
@timeshift92 please close the report if you find it works fine :)

**Comment by timeshift92** [comment]
I didn't understand right away, thanks, everything is fine =)
