### ISSUE TITLE
blazor wasm only (no server side blazor) can't get auth schemes

### ISSUE THREAD

**Issue by seertenedos** [servicetitan/Stl.Fusion#408]
I based my code on a new dotnet 6 wasm blazor project and as far as i can tell i implemented everything needed on both side trying my hardest to work out the parts that were serverside blazor in the samples vs wasm blazor and got the an app mostly working very similar to the blazor sample but the auth dropdown does not work because the schema list is empty.  looking at the sample since it ran the host page serverside it uses c# code on the server to get the list of schemas using 
```
var authSchemas = await _serverAuthHelper.GetSchemas(HttpContext);
    var sessionId = _serverAuthHelper.Session.Id.Value;
```
and then 
```
<script>
        window.FusionAuth.schemas = "@authSchemas";
        window.FusionAuth.sessionId = "@sessionId";
    </script>
```
to set varable even the wasm version can access but if you are running a wasm with no serverside blazer the host page is only index.html so can't contain the c# serverside code to extract the values above.  

Can you provide instructions or sample for a blazer example with out serverside blazer and auth support?

**Comment by alexyakunin** [comment]
@seertenedos please check out `SignInDropdown.razor` from TodoApp sample. Here is what you need to get the list of schemas both on the client & on the server:

![image](https://user-images.githubusercontent.com/1673423/152619257-56b6077b-a541-4945-9b59-047d207adf59.png)

**Comment by alexyakunin** [comment]
Also, sorry for noticing this pretty late. Please LMK if it helps - I'll close the issue once you confirm this solves the problem.

**Comment by alexyakunin** [comment]
Ok, I guess I am closing this issue...
