### ISSUE TITLE
A DateTime value was incorrectly passed to the server in Korean.

### ISSUE THREAD

**Issue by dimohy** [servicetitan/Stl.Fusion#488]
in Korean,

The DateTime is sent to the server like this:

```
2022. 7. 29. 오전 12:00:00
```
![image](https://user-images.githubusercontent.com/58620778/181700358-004935f1-2b3f-4904-aec6-362e92d039bc.png)

Looks like I'll have to send it like this:

2022-07-29T00:00:00

This value is the log delivered to 'HelloBlazorHybrid' 'Fetch Data' of 'Stl.Fusion.Samples' and can be checked:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:7464/api/weatherForecast/getForecast?startDate=2022.+7.+29.+%EC%98%A4%EC%A0%84+12%3A00%3A00 - - - 400 - application/problem+json;+charset=utf-8 0.4104ms
```

It looks like it should be delivered like this:

```
https://localhost:7464/api/weatherForecast/getForecast?startDate=2022-07-29T00:00:00
```

![image](https://user-images.githubusercontent.com/58620778/181701241-1b994ca0-ca62-4c0d-9e7e-1591e7eefb3c.png)

**Comment by alexyakunin** [comment]
So overall, this is the underlying cause: https://github.com/canton7/RestEase/issues/140

**Comment by alexyakunin** [comment]
There are two places in Fusion where RestEase client is created, I fixed both: https://github.com/servicetitan/Stl.Fusion/commit/24fee76eb60a99234171189a9bb806c7f6440a5e
