### ISSUE TITLE
Use SourceGenerator instead of `Castle.DynamicProxy` to create proxy types?

### ISSUE THREAD

**Issue by AlseinX** [servicetitan/Stl.Fusion#67]
When a client is published to a platform that does not support `System.Reflection.Emit`, (eg. IL2CPP in Unity, AOT compiled on iOS, futural Blazor based on Mono AOT, or any other AOT scenes.), dynamic proxy will surely not work. Thus static proxy should be used instead in order to cover more scenes. (It also helps a lot in performance.)

.NET 5 introduces a new SourceGenerator as an expanded feature of code analyzer, which allows code analyzers to generate additional sources to be compiled alongside the project. It can also be used as a code analyzer to validate the code of computed services (eg. Every method marked with `ComputeMethodAttribute` should be declared to be virtual and return some `Task`.).

There are more mature alternatives to SourceGenerator such as [Mono.Cecil](https://github.com/jbevain/cecil/) (that [Fody](https://github.com/Fody/Home) uses to generate [proxies](https://github.com/kswoll/sexy-proxy)), and [Roslyn](https://github.com/dotnet/roslyn) that [Orleans](https://github.com/dotnet/orleans) uses to generate [proxies](https://www.nuget.org/packages/Microsoft.Orleans.CodeGenerator.MSBuild/). They could also be used before .NET 5 and C# 9.0 is formally released.

**Comment by alexyakunin** [comment]
Yeah, I totally support this - honestly, I use Castle.DynamicProxy solely because I wanted to prototype this faster. I totally understand it negatively impacts the performance + won't work in scenarios you've described.

I am absolutely sure we'll have this at some point, the only question is when. But if someone wants to take on this, I can explain _everything_ you need to implement this.

**Comment by alexyakunin** [comment]
@AlseinX ^

**Comment by alexyakunin** [comment]
+ Yeah, I'd try to bet on Source Generators vs other options - e.g. weaving the assembly is nice, but this adds a fair amount of extra time, and since source generators are almost there, I'd rather invest into a modern approach right in the beginning.

**Comment by alexyakunin** [comment]
This is done in v5.X branch.
