### ISSUE TITLE
Add Stl.Async-way of awaiting WaitHandle

### ISSUE THREAD

**Issue by AliveDevil** [servicetitan/Stl.Fusion#672]
I'd like to see some general-purpose ready-to-use implementation of `Task WaitOneAsync(this WaitHandle, CancellationToken)`.
Maybe going as far as returning a ValueTask, though that may be challenging here.

Proposed API:
```
Task WaitOneAsync(this WaitHandle, CancellationToken = default)
Task WaitOneAsync(this WaitHandle, int Timeout, CancellationToken = default)
```

**Comment by AliveDevil** [comment]
If this is a worthwhile addition, I can check to implement this in the not-so distant future.

**Comment by alexyakunin** [comment]
Hi, sorry, just noticed this - IMO this can wait. As far as I remember, `Stl.*` doesn't await on `WaitHandle`-s, so I'd rather postpone this until it's going to be necessary.

**Comment by alexyakunin** [comment]
@AliveDevil ^

**Comment by alexyakunin** [comment]
Closing this.

**Comment by alexyakunin** [comment]
Closing this.
