### ISSUE TITLE
Add step-by-step tutorial

### ISSUE THREAD

**Issue by alexyakunin** [servicetitan/Stl.Fusion#9]
I'm thinking of the following approach: 
* Root-level "tutorial" folder contains numbered sections (p1_simple_computed, p2_[...], etc.)
* Section = a directory with a single file (or maybe N files, if needed) + readme.md
* Launcher = https://github.com/dotnet/try

**Comment by yakunins** [comment]
I guess the easy way for any user is to 
1) checkout example's repo (hello world), 
2) compile and run it locally in minimal amount of time

**Comment by alexyakunin** [comment]
> I guess the easy way for any user is to
> 
> 1. find a link to example's repo
> 2. checkout example's repo (hello world),
> 3. compile and run it locally in minimal amount of time

Yes, that's exactly how it works, but Tutorial is still needed.

**Comment by alexyakunin** [comment]
Done.
